Add #![no_std] compatibility
SoftbearStudios/bitcode pull request #26
Opened 2024-04-19 04:53 UTC by poshcoe

Adds `#![no_std]` (with `alloc`) compatibility by introducing `"std"` cargo feature.

I'm interested in evaluating bitcode in embedded applications. I found adding support relatively painless, most of the changes are swapping `use std::*` for `use::core::*`, and adding explicit use of `alloc`.

Notable changes:
* `HashMap` and `HashSet` implementations for `Decode` and `Encode` are disabled for `no_std`
* Added an unrelated improvement to the `thread_local` [here](https://github.com/SoftbearStudios/bitcode/compare/main...poshcoe:bitcode:no-std-compat?expand=1#diff-d47e861d674c037988d4f1bcf5bba333e59a3b37b42346c537fa0b3da7f09081R241), utilising the const syntax which should improve efficiency by avoiding runtime initialisation checks.
* As `thread_local!` is `std`-only, I added a separate [`impl_u8!`](https://github.com/SoftbearStudios/bitcode/compare/main...poshcoe:bitcode:no-std-compat?expand=1#diff-d47e861d674c037988d4f1bcf5bba333e59a3b37b42346c537fa0b3da7f09081R274) which falls-back to allocating the "scratch space" on each `pack8`/`unpack8` call. See below images for benchmarks on the impact of this change (`target_arch = "x86_64"`).

`cargo +nightly bench bench_pack`:

![Screenshot_20240419_104158](https://github.com/SoftbearStudios/bitcode/assets/26864647/b90c0772-f5a6-4dc1-a75d-656eb3fa5b0e)

`cargo +nightly bench bench_unpack_u`:

![Screenshot_20240419_124131](https://github.com/SoftbearStudios/bitcode/assets/26864647/e6c41c32-0e4f-4bea-a779-44811aaf8186)

At a glance the performance impact is minimal, resulting in a < 1% average performance deficit on both pack and unpack without `std`.

It remains to be seen if bitcode performs well on no_std target architectures. I'll likely be testing this in the near future.

2024-04-19 06:31 UTC, finnbear commented
Thanks for the PR! LGTM. In the interest of not inadvertently breaking `#![no_std]` in the future, is it possible to add a CI job that runs a subset of the tests?

2024-04-19 06:55 UTC, poshcoe commented
> In the interest of not inadvertently breaking `#![no_std]` in the future, is it possible to add a GitHub Actions job that runs a subset of the tests?

Sure, I'll tack it on along with fixes for the lints

2024-04-19 08:25 UTC, poshcoe commented
I also took the chance to enable compat of the "serde", "glam" and "arrayvec" features with #![no_std].

The new test therefore enables `--features derive,serde,glam,arrayvec`

2024-04-19 15:23 UTC, finnbear commented on Cargo.toml
>  features = [ "derive", "serde" ]
Please add `std` here just to be safe :ok_hand:

2024-04-19 15:24 UTC, finnbear approved these changes
Thanks very much! :rocket:

2024-04-20 01:21 UTC, caibear requested changes

2024-04-20 01:21 UTC, caibear commented on bitcode_derive/src/lib.rs
> +extern crate alloc;
bitcode_derive should be able to unconditionally use std even if bitcode can't

2024-04-20 01:21 UTC, caibear commented on src/derive/map.rs
> +    crate::bench_encode_decode!(btree_map: BTreeMap<_, _>);
This can be simplified to:
```rust
    crate::bench_encode_decode!(btree_map: BTreeMap<_, _>);
    #[cfg(feature = "std")]
    crate::bench_encode_decode!(hash_map: HashMap<_, _>);
```

2024-04-20 01:21 UTC, caibear commented on src/derive/vec.rs
> +    );
Another simplification:
```rust
    crate::bench_encode_decode!(
        btree_set: BTreeSet<_>,
        linked_list: LinkedList<_>,
        vec: Vec<_>,
        vec_deque: VecDeque<_>
    );
    #[cfg(feature = "std")]
    crate::bench_encode_decode!(hash_set: HashSet<_>);
```

2024-04-20 01:21 UTC, caibear commented on src/pack_ints.rs
> +            let mut bytes = CowSlice::with_allocation(allocation);
Vec::with_capacity is pointless here since it will only be grown once (will allocate same amount as with_capacity).
```rust
let mut bytes = CowSlice::default();
```

2024-04-20 01:24 UTC, caibear commented
Build is failing because cargo fmt's output changed between nightly-2023-04-25 and your rust version.

2024-04-20 01:50 UTC, caibear commented
Ok, I've fixed the issues I noticed.

2024-04-20 01:52 UTC, poshcoe commented
thanks!

2024-04-20 01:53 UTC, caibear approved these changes

2024-04-20 02:16 UTC, merged